name: estagio_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  provider: ^4.1.0
  email_validator: ^1.0.5
  font_awesome_flutter: 8.5.0
  intl: ^0.16.1
  path_provider: ^1.6.14
  file_picker: ^1.13.3
  dio: 3.0.10
  directory_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo_regular.ttf